server:
  port: 15000
  error:
    include-exception: false
    include-stacktrace: never

general:
  api-base-url: ${API_BASE_URL}
  app-base-url: ${APP_BASE_URL}
  app-private-base-url: ${APP_PRIVATE_BASE_URL}
  static-base-url: ${STATIC_BASE_URL}

spring:
  application:
    name: eco-picker-api

security:
  jwt:
    issuer: ${JWT_ISSUER}
    access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:600000}
    refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:1800000}

gemini:
  app-key: ${APP_KEY}

logging:
  level:
    root: INFO
    com.eco_picker: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html