server:
  port: 15000
  error:
    include-exception: false
    include-stacktrace: never

general:
  api-base-url: ${API_BASE_URL}
  app-base-url: ${APP_BASE_URL}
  app-private-base-url: ${APP_PRIVATE_BASE_URL}
  static-base-url: ${STATIC_BASE_URL}

spring:
  application:
    name: eco-picker-api
