server:
  port: 15000
  error:
    include-exception: false
    include-stacktrace: never

general:
  api-base-url: ${API_BASE_URL}
  app-base-url: ${APP_BASE_URL}
  static-base-url: ${STATIC_BASE_URL}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: eco-picker-api
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html,.js
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    debug: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO_GENERATE_TYPE}
    show-sql: ${DB_USE_DEBUG_MODE}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${DB_USE_DEBUG_MODE}
        use_sql_comments: ${DB_USE_DEBUG_MODE}


file:
  max-file-size-mb: 5

security:
  jwt:
    issuer: ${JWT_ISSUER}
    access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:600000}
    refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:1800000}

gemini:
  app-key: ${APP_KEY}

logging:
  level:
    root: INFO
    com.eco_picker: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html