server:
  port: 15000
  address: 0.0.0.0
  error:
    include-exception: false
    include-stacktrace: never

general:
  api-base-url: ${API_BASE_URL:https://eco-picker.com/api}
  app-base-url: ${APP_BASE_URL:https://eco-picker.com/app}
  static-base-url: ${STATIC_BASE_URL:https://eco-picker.com/static}

spring:
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:file:.env[.properties]
  application:
    name: eco-picker-api
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html,.js
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:ecopicker@gmail.com}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  sql:
    init:
      mode: always
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO_GENERATE_TYPE:update}
    show-sql: ${DB_USE_DEBUG_MODE:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${DB_USE_DEBUG_MODE:false}
        use_sql_comments: ${DB_USE_DEBUG_MODE:false}
    defer-datasource-initialization: true


file:
  max-file-size-mb: 5

security:
  jwt:
    issuer: ${JWT_ISSUER:ecopicker@gmail.com}
    access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:600000}
    refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:1800000}

gemini:
  app-key: ${APP_KEY}

logging:
  level:
    root: INFO`
    com.eco_picker: DEBUG
    org.hibernate.SQL: ${DB_SQL_LOGGING_LEVEL:INFO}
    org.hibernate.orm.jdbc.bind: ${DB_SQL_PARAMETER_LOGGING_LEVEL:INFO}

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
  paths-to-match:
    - /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /api/actuator
  endpoint:
    health:
      show-details: always