TRUNCATE TABLE garbage;
INSERT INTO garbage (user_id, id, `name`, category, latitude, longitude, collected_at, created_at, updated_at, memo)
VALUES (1, 1, 'Plastic bottle', 'PLASTIC', 43.69087654257335, -79.42937900697125, '2023-10-27 00:00:00', NOW(), null,
        null),
       (1, 2, 'Aluminum can', 'METAL', 43.69087654257335, -79.42937900697125, '2023-10-27 00:00:00', NOW(), null, null),
       (1, 3, 'Glass jar', 'GLASS', 43.69087654257335, -79.42937900697125, '2023-10-27 00:00:00', NOW(), null, null),
       (1, 4, 'Cardboard box', 'CARDBOARD_PAPER', 43.69087654257335, -79.42937900697125, '2023-10-27 00:00:00', NOW(),
        null, null),
       (1, 5, 'Apple core', 'FOOD_SCRAPS', 43.69087654257335, -79.42937900697125, '2023-10-27 00:00:00', NOW(), null,
        null),
       (1, 6, 'Grass clippings', 'ORGANIC_YARD_WASTE', 43.69087654257335, -79.42937900697125, '2023-10-27 00:00:00',
        NOW(), null,
        null),
       (1, 7, 'Broken ceramic plate', 'OTHER', 43.69087654257335, -79.42937900697125, '2023-10-27 00:00:00', NOW(),
        null, null);
TRUNCATE TABLE newsletter;
INSERT INTO newsletter (title, content, source, category, published_at, created_at, updated_at)
VALUES ('Canada Announces New Recycling Targets',
        'The Canadian government has announced ambitious new recycling targets, aiming to recycle 90% of all packaging by 2030. The plan includes investments in infrastructure and technology, as well as measures to encourage businesses and consumers to adopt more sustainable practices.',
        'https://www.cbc.ca/news/canada/canada-announces-new-recycling-targets-1.6645313', 'NEWS',
        '2023-10-27 00:00:00', NOW(), NULL),
       ('South Korea Launches National Recycling Campaign',
        'South Korea has launched a nationwide recycling campaign aimed at increasing awareness and participation in waste reduction and recycling efforts. The campaign features public service announcements, educational materials, and community events.',
        'https://www.koreatimes.co.kr/www/news/nation/2023/10/123_348260.html', 'NEWS', '2023-10-26 00:00:00', NOW(),
        NULL),
       ('New Study Highlights Environmental Impact of Plastic Waste',
        'A recent study published in the journal Nature has revealed the significant environmental impact of plastic waste, particularly in the ocean. The study found that plastic pollution is harming marine ecosystems and contributing to climate change.',
        'https://www.nature.com/articles/s41586-023-06724-w', 'NEWS', '2023-10-25 00:00:00', NOW(), NULL),
       ('Recycle Right!',
        'Learn how to properly recycle different materials like paper, plastic, and glass. This guide explains the different recycling bins, what items belong in each, and how to prepare your recyclables for collection.',
        'https://www.recyclingcouncil.org/recycle-right/', 'EDUCATION', '2023-10-27 00:00:00', NOW(), NULL),
       ('The Journey of a Recycled Bottle',
        'Follow the fascinating journey of a plastic bottle from your recycling bin to its transformation into new products. Learn about the different stages of recycling and how recycled materials are used to create new items.',
        'https://www.terracycle.com/en-US/learn/the-journey-of-a-recycled-bottle', 'EDUCATION', '2023-10-26 00:00:00',
        NOW(), NULL),
       ('Fun Ways to Reduce Waste with Kids',
        'Engage children in environmental stewardship with fun activities like crafting with recycled materials, composting food scraps, and learning about the importance of conserving water and energy.',
        'https://www.epa.gov/recycle/kids-waste-free-living', 'EDUCATION', '2023-10-25 00:00:00', NOW(), NULL),
       ('Family Eco-Challenge',
        'Join a fun, family-friendly challenge to reduce your environmental impact. Participants will be given a list of eco-friendly tasks to complete throughout the month, from using reusable bags to planting a tree. Prizes will be awarded to the most environmentally conscious families!',
        'https://www.eventbrite.ca/e/family-eco-challenge-tickets-70708920865', 'EVENT', '2023-10-27 00:00:00', NOW(),
        NULL),
       ('Online Workshop: Composting 101',
        'Learn how to start your own compost bin at home! This interactive online workshop will cover everything from the basics of composting to choosing the right materials and composting methods. Register now for a free session!',
        'https://www.greenliving.ca/events/online-workshop-composting-101', 'EVENT', '2023-10-26 00:00:00', NOW(),
        NULL),
       ('Online Workshop: Composting 101',
        'Learn how to start your own compost bin at home! This interactive online workshop will cover everything from the basics of composting to choosing the right materials and composting methods. Register now for a free session!',
        'https://www.greenliving.ca/events/online-workshop-composting-101', 'EVENT', '2023-10-26 00:00:00', NOW(),
        NULL),
       ('Online Workshop: Composting 101',
        'Learn how to start your own compost bin at home! This interactive online workshop will cover everything from the basics of composting to choosing the right materials and composting methods. Register now for a free session!',
        'https://www.greenliving.ca/events/online-workshop-composting-101', 'EVENT', '2023-10-26 00:00:00', NOW(),
        NULL),
       ('Online Workshop: Composting 101',
        'Learn how to start your own compost bin at home! This interactive online workshop will cover everything from the basics of composting to choosing the right materials and composting methods. Register now for a free session!',
        'https://www.greenliving.ca/events/online-workshop-composting-101', 'EVENT', '2023-10-26 00:00:00', NOW(),
        NULL),
       ('Volunteer at a Local Recycling Center',
        'Make a difference in your community by volunteering at your local recycling center. Volunteers help sort materials, organize recycling bins, and educate others about recycling best practices. Sign up for a shift today!',
        'https://www.volunteermatch.org/search/opp?q=recycling+center+volunteer&l=Canada', 'EVENT',
        '2023-10-25 00:00:00', NOW(), NULL);
