name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Debug Secrets
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}"
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}"
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"
          echo "GEMINI_APP_KEY=${{ secrets.GEMINI_APP_KEY }}"
          echo "GCE_PROJECT=${{ secrets.GCE_PROJECT }}"
          echo "GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}"

      - name: Build with Gradle
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          GEMINI_APP_KEY: ${{ secrets.GEMINI_APP_KEY }}
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -f ./docker/Dockerfile -t gcr.io/${{ secrets.GCE_PROJECT }}/eco-picker-api:latest .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCE_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCE_PROJECT }}/eco-picker-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCE_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Google Compute Engine
        run: |
          gcloud compute ssh YOUR_INSTANCE_NAME --zone YOUR_INSTANCE_ZONE --command "
          sudo docker pull gcr.io/${{ secrets.GCE_PROJECT }}/eco-picker-api:latest &&
          sudo docker stop eco-picker-api || true &&
          sudo docker rm eco-picker-api || true &&
          sudo docker run -d --name eco-picker-api -p 15000:15000 gcr.io/${{ secrets.GCE_PROJECT }}/eco-picker-api:latest
          "